using PyCall

launch = pyimport("ansys.mapdl.core").launch_mapdl

m = launch()

elem_size = 0.0005
duration = 1.0
n_substeps = 5

m.prep7()

m.title("EBM Simulation")
m.block(0, 0.1, 0, 0.06, -0.08, 0)

m.mptemp(1, 300)
m.mpdata("ex", 1, 1, 2.0e11)
m.mp("dens", 1, 7850)
m.mp("alpx", 1, 1.23e-5)
m.mp("nuxy", 1, 0.3)
m.mp("kxx", 1, 33)
m.mp("c", 1, 561)
m.mp("murx", 1, 1)
m.mp("reft", 1, 300)

m.et(1, "solid70")
m.esize(elem_size)
m.mshkey("1")
m.mshape("0", "3d")
m.vmesh("all")

m.lsclear("all")

m.esel("s", "cent", "z", -elem_size, 0)

# m.eplot()

heat_source_def = """
*DEL,_FNCNAME
*DEL,_FNCMTID
*DEL,_FNCCSYS
*SET,_FNCNAME,'HFLUX'
*SET,_FNCCSYS,0

! Heat source function definition table generated by Function Editor in the GUI
*DIM,%_FNCNAME%,TABLE,6,26,1,,,,%_FNCCSYS%  
!   
! Begin of equation: 4e7*exp(-3*(({Y}-0.03)^2+({X}-0.02-0.02*   
! {TIME})^2)/0.005^2)   
*SET,%_FNCNAME%(0,0,1), 0.0, -999   
*SET,%_FNCNAME%(2,0,1), 0.0 
*SET,%_FNCNAME%(3,0,1), 0.0 
*SET,%_FNCNAME%(4,0,1), 0.0 
*SET,%_FNCNAME%(5,0,1), 0.0 
*SET,%_FNCNAME%(6,0,1), 0.0 
*SET,%_FNCNAME%(0,1,1), 1.0, -1, 0, 0, 0, 0, 0  
*SET,%_FNCNAME%(0,2,1), 0.0, -2, 0, 1, 0, 0, -1 
*SET,%_FNCNAME%(0,3,1),   0, -3, 0, 1, -1, 2, -2
*SET,%_FNCNAME%(0,4,1), 0.0, -1, 0, 3, 0, 0, -3 
*SET,%_FNCNAME%(0,5,1), 0.0, -2, 0, 1, -3, 3, -1
*SET,%_FNCNAME%(0,6,1), 0.0, -1, 0, 0.03, 0, 0, 3   
*SET,%_FNCNAME%(0,7,1), 0.0, -3, 0, 1, 3, 2, -1 
*SET,%_FNCNAME%(0,8,1), 0.0, -1, 0, 2, 0, 0, -3 
*SET,%_FNCNAME%(0,9,1), 0.0, -4, 0, 1, -3, 17, -1   
*SET,%_FNCNAME%(0,10,1), 0.0, -1, 0, 0.02, 0, 0, 2  
*SET,%_FNCNAME%(0,11,1), 0.0, -3, 0, 1, 2, 2, -1
*SET,%_FNCNAME%(0,12,1), 0.0, -1, 0, 0.02, 0, 0, 1  
*SET,%_FNCNAME%(0,13,1), 0.0, -5, 0, 1, -1, 3, 1
*SET,%_FNCNAME%(0,14,1), 0.0, -1, 0, 1, -3, 2, -5   
*SET,%_FNCNAME%(0,15,1), 0.0, -3, 0, 2, 0, 0, -1
*SET,%_FNCNAME%(0,16,1), 0.0, -5, 0, 1, -1, 17, -3  
*SET,%_FNCNAME%(0,17,1), 0.0, -1, 0, 1, -4, 1, -5   
*SET,%_FNCNAME%(0,18,1), 0.0, -3, 0, 1, -2, 3, -1   
*SET,%_FNCNAME%(0,19,1), 0.0, -1, 0, 0.005, 0, 0, 0 
*SET,%_FNCNAME%(0,20,1), 0.0, -2, 0, 2, 0, 0, -1
*SET,%_FNCNAME%(0,21,1), 0.0, -4, 0, 1, -1, 17, -2  
*SET,%_FNCNAME%(0,22,1), 0.0, -1, 0, 1, -3, 4, -4   
*SET,%_FNCNAME%(0,23,1), 0.0, -1, 7, 1, -1, 0, 0
*SET,%_FNCNAME%(0,24,1), 0.0, -2, 0, 4e7, 0, 0, -1  
*SET,%_FNCNAME%(0,25,1), 0.0, -3, 0, 1, -2, 3, -1   
*SET,%_FNCNAME%(0,26,1), 0.0, 99, 0, 1, -3, 0, 0
! End of equation: 4e7*exp(-3*(({Y}-0.03)^2+({X}-0.02-0.02*{TIME})^2)/0.005^2)

/solu
sfe, all, , hflux, , %HFLUX%
"""
m.run_multiline(heat_source_def)

# m.eplot()

m.slashsolu()
m.antype("4")
m.outres("all", "all")
m.kbc(1)
m.timint("on")
m.tintp(0.005, 0, 0, 1, 0.5, 0.2)
m.autots("off")

m.time(duration)
m.nsubst(n_substeps, n_substeps, n_substeps)
m.solve()

m.finish()

m.post1()
for i in 1:5
    m.set(1, i)
    m.post_processing.plot_nodal_temperature()
    sleep(0.5)
end