FROM ubuntu:latest

# COPY ./*  /home/test/

# WORKDIR /home/test

# RUN ./test9.sh

# CMD ["python3", "/home/test/test9.py"]

# FROM python:3.8-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN apt update\
 && apt install -y python3 python3-pip python3-numpy python3-opencv\
 && pip3 install -r requirements.txt

COPY . .

CMD ["python3", "test9.py"]
